apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    project: p3-saiap
spec:
  type: NodePort
  selector:
    app: prometheus
    project: p3-saiap
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
    nodePort: 30090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
    project: p3-saiap
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s 
      # By default, scrape targets every 15 seconds. 
      # changing to 5s needs more cpu to calculate.

      # Attach these labels to any time series or alerts when communicating with
      # external systems (federation, remote storage, Alertmanager).
      external_labels:
        monitor: 'codelab-monitor'

    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: 'prometheus'
      # Override the global default and scrape targets from this job every 5 seconds.
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090'] 

      - job_name: 'tfserving'
        # Override the global default and scrape targets from this job every 5 seconds.
        scrape_interval: 30s
        metrics_path: '/monitoring/prometheus/metrics'
        static_configs:
          - targets: ['p3-saiap-tfserving:32211']

      - job_name: 'node_exporter'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9100']

      - job_name: 'gateway'
        scrape_interval: 20s
        metrics_path: '/metrics'
        static_configs:
        - targets: ['p3-saiap-gateway:3333']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
    project: p3-saiap
spec:
  selector:
    matchLabels:
      app: prometheus
      project: p3-saiap
  template:
    metadata:
      labels:
        app: prometheus
        project: p3-saiap
      annotations:
        configmap-sha1sum: f25c33ac05765d475ae90ca58cfd2bdb18a83119
    spec:
      containers:
      - name: prometheus
        image: harbor.wzs.wistron.com.cn/prometheus/prometheus:v2.13.0
        command:
        - /bin/prometheus
        args:
        - --config.file=/prometheus.yml
        volumeMounts: 
        # Actual used volume in this pod
        - name: prometheus-config
          mountPath: /prometheus.yml
          # subPath is to avoid make a new folder above the yml 
          subPath: prometheus.yml
        - name: prometheus-data
          mountPath: /prometheus/data
        ports:
        - containerPort: 9090
      volumes: 
      # Back up data from container in local server
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-data
        hostPath:
        # the directory below should "chown nobody/nogroup", not be root/root
          path: /d/prometheus-data