apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: logging
  labels:
    app: loki-app
data: 
  config.yml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s

    schema_config:
      configs:
      - from: 2019-10-01
        store: boltdb
        object_store: filesystem
        schema: v9
        index:
          prefix: index_
          period: 168h

    storage_config:
      boltdb:
        directory: /data/loki/index

      filesystem:
        directory: /data/loki/chunks

    limits_config:
      enforce_metric_name: false

    chunk_store_config:
      max_look_back_period: 0

    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h
