apiVersion: v1
kind: Service
metadata:
  namespace: logging
  name: loki
spec:
  type: NodePort
  selector:
    app: loki-app
  ports:
  - name: loki-api
    port: 3100
    targetPort: loki-api
    nodePort: 31000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-app
  serviceName: loki
  template:
    metadata:
      labels:
        app: loki-app
        namespace: logging
    spec:
      containers:
      - name: loki
        image: grafana/loki:v0.3.0
        args:
        - -config.file=/etc/loki/config.yml
        ports:
        - name: loki-api
          containerPort: 3100
        livenessProbe:
          httpGet:
            path: /ready
            port: loki-api
          initialDelaySeconds: 45
        readinessProbe:
          httpGet:
            path: /ready
            port: loki-api
          initialDelaySeconds: 45
        volumeMounts:
        - name: data
          mountPath: /data/loki
        - name: loki-config
          mountPath: /etc/loki
      volumes:
      - name: loki-config
        configMap:
          name: loki-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
