apiVersion: v1
kind: Service
metadata:
  namespace: simple-conv
  name: simple-conv-alu-m2
  labels: 
    app: simple-conv
spec:
  type: NodePort
  externalIPs: 
  - 10.41.65.78
  selector:
    app: simple-conv
  ports:
  - name: tb
    port: 30606
    targetPort: tb
    nodePort: 30606