apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: logging
  name: promtail
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - services
    - pod
    verbs:
    - get
    - watch
    - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: logging
  name: promtail
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: logging
  name: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: default
roleRef:
    kind: ClusterRole
    name: promtail
    apiGroup: rbac.authorization.k8s.io